# Generated by Django 3.0.8 on 2020-07-29 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_register33'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='email',
            new_name='email_id',
        ),
    ]
