# Generated by Django 3.0.8 on 2020-07-29 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200729_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='email_id',
            new_name='email',
        ),
    ]
