# Generated by Django 3.0.8 on 2020-08-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_register33_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=30)),
                ('Lastname', models.CharField(max_length=30)),
                ('emailid', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30, null=True, unique=True)),
                ('password', models.CharField(max_length=30, null=True)),
                ('picture', models.FileField(null=True, upload_to='post/')),
                ('date', models.DateField()),
            ],
        ),
    ]
