# Generated by Django 3.0.8 on 2020-08-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200824_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistaccount',
            name='Category',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
