# Generated by Django 3.0.8 on 2020-08-25 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_artistaccount_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistaccount',
            old_name='picture',
            new_name='image',
        ),
    ]
