# Generated by Django 3.0.8 on 2020-08-25 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200825_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistaccount',
            name='Category',
        ),
    ]
