# Generated by Django 3.0.8 on 2020-08-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200825_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistaccount',
            name='image',
            field=models.ImageField(null=True, upload_to='media/post/'),
        ),
    ]
