# Generated by Django 3.0.8 on 2020-08-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200825_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistaccount',
            name='image',
            field=models.FileField(null=True, upload_to='post/'),
        ),
    ]
