# Generated by Django 3.0.8 on 2020-09-02 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200826_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistaccount',
            old_name='password',
            new_name='saleprice',
        ),
        migrations.RemoveField(
            model_name='artistaccount',
            name='Firstname',
        ),
        migrations.RemoveField(
            model_name='artistaccount',
            name='Lastname',
        ),
        migrations.RemoveField(
            model_name='artistaccount',
            name='emailid',
        ),
        migrations.RemoveField(
            model_name='artistaccount',
            name='username',
        ),
        migrations.AddField(
            model_name='artistaccount',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.register33'),
        ),
    ]
