# Generated by Django 3.0.8 on 2020-09-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistaccount',
            name='productname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
