# Generated by Django 3.0.8 on 2020-09-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_artistaccount_productprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistaccount',
            name='saleprice',
            field=models.FloatField(max_length=30, null=True),
        ),
    ]
