# Generated by Django 3.0.8 on 2020-09-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register33',
            name='emailid',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
