# Generated by Django 3.0.8 on 2020-09-18 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20200918_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register33',
            name='emailid',
        ),
    ]
