# Generated by Django 3.0.8 on 2020-09-18 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20200918_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register33',
            name='emailid',
        ),
    ]
