# Generated by Django 3.0.8 on 2020-09-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20200918_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cover_pic',
            field=models.FileField(upload_to='post/'),
        ),
    ]
