# Generated by Django 3.0.8 on 2020-09-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20200918_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cover_pic',
            field=models.FileField(null=True, upload_to='post/'),
        ),
    ]
