# Generated by Django 3.0.8 on 2020-09-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20200918_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register33',
            name='emailid',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
