# Generated by Django 3.0.8 on 2020-09-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_category_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register33',
            name='emailid',
            field=models.CharField(max_length=30),
        ),
    ]
