# Generated by Django 3.0.8 on 2020-09-19 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20200919_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='added_on',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cover_pic',
        ),
    ]
