# Generated by Django 3.0.8 on 2020-09-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20200919_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover_pic',
            field=models.FileField(null=True, upload_to='post/'),
        ),
    ]
