# Generated by Django 3.0.8 on 2020-10-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_artistaccount_inches'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistaccount',
            old_name='Inches',
            new_name='height',
        ),
        migrations.AddField(
            model_name='artistaccount',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
