# Generated by Django 3.0.8 on 2020-10-11 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.register33'),
        ),
    ]
