# Generated by Django 3.0.8 on 2020-10-11 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20201011_1623'),
    ]

    operations = [
        migrations.DeleteModel(
            name='photo',
        ),
    ]
