# Generated by Django 3.0.8 on 2020-10-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20201011_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.FileField(null=True, upload_to='post/'),
        ),
    ]
