# Generated by Django 3.0.8 on 2020-10-11 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_auto_20201011_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='Amount',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Customphoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(null=True, upload_to='post/')),
                ('Imageheight', models.IntegerField(null=True)),
                ('ImageWidth', models.IntegerField(null=True)),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Category')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.register33')),
            ],
        ),
    ]
